### ISSUE TITLE
Change the default red color of side-bar

### ISSUE THREAD

**Issue by suchetaswabhav** [creativetimofficial/now-ui-dashboard-angular#5]
Hi,

I want to change the default red-color of the sidebar. I did Inspect and got this css -

      .sidebar[data-color="red"]:after,
      .off-canvas-sidebar[data-color="red"]:after {
         background: #FF3636; 
        }

But after changing its background color, it  still doesn't change. Please help.

**Comment by chelaruc** [comment]
@suchetaswabhav you need to go to `src/app/layouts/admin-layout/admin-layout.component.html` file and on line 2 you have `data-color="red"`. That's the place where you need to change the color. We implemented 5 options: blue, green, orange, red and yellow.

Best,
Ciprian
