### ISSUE TITLE
Unable to include material design alongside theme 

### ISSUE THREAD

**Issue by poulav** [creativetimofficial/now-ui-dashboard-angular#7]
Hey, I am unable to use material design components and modules along with this theme, can you please suggest how do I integrate it?
Thanks.

**Comment by chelaruc** [comment]
Hi, @poulav. Thank you for using our product. This product is built with another design and if you want to use material design, check this dashboard: https://www.creative-tim.com/product/material-dashboard-angular2 . Otherwise, we can't help you with the integration.
